import { CcBar } from '../../shapes/helpers';
import { dimModeEnum, ProfileSizeSettings } from '.';
export declare class ShapeManager {
  readonly isDirty: boolean;
  readonly area: number;
  readonly height: number;
  readonly width: number;
  readonly isEmpty: boolean;
  readonly ccBar: CcBar;
  shapeMode: dimModeEnum;
  darkMode: boolean;
  preventScale: boolean;
  asSimpleView: boolean;
  enLangMode: boolean;
  profileSize: ProfileSizeSettings;
  barNormal: string | HTMLImageElement;
  handleColor: string;
  addFrame(linePath: any[]): void;
  openFile(data: string, remember?: boolean): void;
  moveShapeToCenter(dstContainer?: HTMLElement): void;
  toData(): string | undefined;
  toSimpleData(): string | undefined;
  toNoDimData(): string | undefined;
  toData2d(): string;
  toDataCC(): string;
  setFrameSize(width: number, height: number): void;
  exportJson(): void;
  export(name?: string): void;
  export3dJson(asFile?: boolean): string | void;
  remove(): void;
  clear(refresh?: boolean): void;
}
