export declare enum HardwareShape {
  Hinge = 'Hinge',
  HingeOnCircle = 'HingeOnCircle',
  HingePro = 'HingePro',
  Handle = 'Handle',
  Handle2 = 'Handle2',
  CommercialHandle = 'CommercialHandle',
  CommercialHandle2 = 'CommercialHandle2',
  CommercialHandle3 = 'CommercialHandle3',
  CommercialHandle4 = 'CommercialHandle4',
  CommercialHandle5 = 'CommercialHandle5',
  CommercialHandle6 = 'CommercialHandle6',
  CommercialHandle7 = 'CommercialHandle7',
  CommercialHandle8 = 'CommercialHandle8',
  CommercialHandle9 = 'CommercialHandle9',
  CommercialHandle10 = 'CommercialHandle10',
  CommercialHandle11 = 'CommercialHandle11',
  CommercialHandle12 = 'CommercialHandle12',
  HandleForFold = 'HandleForFold',
  HandleForSlide = 'HandleForSlide',
  KfcHandle = 'KfcHandle',
  CrossHandle = 'CrossHandle',
  Lock = 'Lock',
  Lock2 = 'Lock2',
}
