import { environment } from '../environments/environment';

const lines = [
  {
    tag: "SLIDING",
    models: [
      "SLIDING-DOBLERIEL_CUATRO_HOJA_80",
      "SLIDING-DOBLERIEL_CUATRO_HOJA_80_ZAPATA",
      "SLIDING-DOBLERIEL_CUATRO_HOJA_98",
      "SLIDING-DOBLERIEL_CUATRO_HOJA_98_ZAPATA",
      "SLIDING-DOBLERIEL_DOS_HOJA_80",
      "SLIDING-DOBLERIEL_DOS_HOJA_80_ZAPATA",
      "SLIDING-DOBLERIEL_DOS_HOJA_98",
      "SLIDING-DOBLERIEL_DOS_HOJA_98_ZAPATA",
      "SLIDING-DOBLERIEL_TRES_HOJA_80",
      "SLIDING-DOBLERIEL_TRES_HOJA_80_ZAPATA",
      "SLIDING-DOBLERIEL_TRES_HOJA_98",
      "SLIDING-DOBLERIEL_TRES_HOJA_98_ZAPATA",
      "SLIDING-TRIPLERIEL_SEIS_HOJA_80",
      "SLIDING-TRIPLERIEL_SEIS_HOJA_98",
      "SLIDING-TRIPLERIEL_TRES_HOJA_80",
      "SLIDING-TRIPLERIEL_TRES_HOJA_98",
    ]
  },
  {
    tag: "ANDES",
    models: [
      "ANDES-ABATIR_S38",
      "ANDES-DOBLERIEL_2_HOJAS_54",
      "ANDES-DOBLERIEL_2_HOJAS_66",
      "ANDES-DOBLERIEL_3_HOJAS_54",
      "ANDES-DOBLERIEL_3_HOJAS_66",
      "ANDES-DOBLERIEL_4_HOJAS_54",
      "ANDES-DOBLERIEL_4_HOJAS_66",
      "ANDES-MARCO_FIJO_S38",
      "ANDES-MONORIEL_HOJA_54",
      "ANDES-MONORIEL_HOJA_54_DIV_HORIZONTAL",
      "ANDES-MONORIEL_HOJA_66",
      "ANDES-MONORIEL_HOJA_66_DIV_HORIZONTAL",
      "ANDES-PROYECTANTE_S38",
    ]
  },
  {
    tag: "ZENIA",
    models: [
      "ZENIA-ZENIA_CC",
      "ZENIA-ZENIA_CC_MIR",
      "ZENIA-ZENIA_CCCC",
      "ZENIA-ZENIA_CCCC_MIR",
      "ZENIA-ZENIA_CF",
      "ZENIA-ZENIA_CF_MIR",
      "ZENIA-ZENIA_CFC",
      "ZENIA-ZENIA_CFC_MIR",
      "ZENIA-ZENIA_FCCF",
      "ZENIA-ZENIA_FCCF_MIR",
      "ZENIA-ZENIA_FCF",
      "ZENIA-ZENIA_FCF_MIR",
    ]
  },
  {
    tag: "S60",
    models: [
      "S60-PUERTA_ABATIR_DOBLE_MARCO_PERIMETRAL_EXTERIOR",
      "S60-PUERTA_ABATIR_DOBLE_MARCO_PERIMETRAL_INTERIOR",
      "S60-PUERTA_ABATIR_DOBLE_PASO_LIBRE_EXTERIOR",
      "S60-PUERTA_ABATIR_DOBLE_PASO_LIBRE_INTERIOR",
      "S60-PUERTA_ABATIR_DOBLE_ZAPATA_EXTERIOR",
      "S60-PUERTA_ABATIR_DOBLE_ZAPATA_INTERIOR",
      "S60-PUERTA_ABATIR_MARCO_PERIMETRAL_EXTERIOR",
      "S60-PUERTA_ABATIR_MARCO_PERIMETRAL_INTERIOR",
      "S60-PUERTA_ABATIR_PASO_LIBRE_EXTERIOR",
      "S60-PUERTA_ABATIR_PASO_LIBRE_INTERIOR",
      "S60-PUERTA_ABATIR_ZAPATA_EXTERIOR",
      "S60-PUERTA_ABATIR_ZAPATA_INTERIOR",
      "S60-PUERTA_OSCILOBATIENTE",
      "S60-VENTANA_ABATIR_DOBLE_EXTERIOR_CON_BISAGRA",
      "S60-VENTANA_ABATIR_DOBLE_EXTERIOR_CON_BRAZO",
      "S60-VENTANA_ABATIR_DOBLE_INTERIOR_CON_BISAGRA",
      "S60-VENTANA_ABATIR_DOBLE_INTERIOR_CON_BRAZO",
      "S60-VENTANA_ABATIR_EXTERIOR_CON_BISAGRA",
      "S60-VENTANA_ABATIR_EXTERIOR_CON_BRAZO",
      "S60-VENTANA_ABATIR_INTERIOR_CON_BISAGRA",
      "S60-VENTANA_ABATIR_INTERIOR_CON_BRAZO",
      "S60-VENTANA_FIJA",
      "S60-VENTANA_OSCILOBATIENTE",
      "S60-VENTANA_PROYECTANTE_EXTERIOR",
    ]
  },
];

export const ventanas = lines.reduce<{ name: string, value: string }[]>((acc, line) => {
  return acc.concat(
    line.models.map(model => {
      return { name: model, value: JSON.stringify(require('../assets/ventanas/' + line.tag + '/' + model + '.json')) };
    })
  );
},
  [],
);

