export declare enum EventType {
    ear_frame_settings = "ear_frame_settings",
    single_track_frame_settings = "single_track_frame_settings",
    double_ears_frame_settings = "double_ears_frame_settings",
    regular_frame_settings = "regular_frame_settings",
    frame_settings = "frame_settings",
    frame_joint_way = "frame_joint_way",
    bar_endpoint = "bar_endpoint",
    bar_modifier = "bar_modifier",
    sash_settings = "sash_settings",
    kfc_sash_settings = "kfc_sash_settings",
    wall_settings = "wall_settings",
    sash_group_settings = "sash_group_settings",
    sash_bar_settings = "sash_bar_settings",
    handle_position_change = "handle_position_change",
    wall_shape_change = "wall_shape_change",
    antitheft_setting = "antitheft_setting",
    frame_bar_dim = "frame_bar_dim",
    top_view_change = "top_view_change",
    corner_joiner_settings = "corner_joiner_settings",
    dim_setting = "dim_setting",
    dim_name_modified = "dim_name_modified"
}
