import { EdgeJointWay } from '../common';
import { HardwareShape } from '../shapes';
import { OpenToward, OpenDirection } from '../shapes/managers';
export declare class SashSettings {
  readonly isPush: boolean;
  readonly isSlide: boolean;
  readonly isFold: boolean;
  readonly handleForFoldHidden: boolean;
  readonly remainingWidth: number;
  readonly handlePosition: any;
  opened: boolean;
  jointWay: EdgeJointWay;
  hasOffset: boolean;
  openDirection: OpenDirection;
  openToward: OpenToward;
  hingeType: HardwareShape;
  hingeCount: number;
  autoHingeOffsets: boolean;
  hingeOffsets: number[];
  handleType: HardwareShape;
  autoHandleOffset: boolean;
  handleOffset: number;
  handleHidden: boolean;
  dimToGroundHidden: boolean;
  isFixed: boolean;
  width: number;
  lockOffset: number;
  slideLockHidden: boolean;
  crescentLockShown: number;
  slideHandleHidden: boolean;
  handleForFoldOffset: number;
}
